# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:

- job: CI
  displayName: 'Continuous Integration'
  pool:
    vmImage: ubuntu-latest

  steps:

  - script: |
      echo "Current directory:"
      pwd

      echo ""
      echo "Files in repository:"
      ls -la

      echo ""
      echo "Docker version:"
      docker --version
    displayName: 'Inspect Azure DevOps agent'

  - script: |
      docker build -t nhidayah26/flask-app-cicd:v1 .
    displayName: 'Build Docker Image'

  - task: Docker@2
    displayName: 'Push Docker Image to Docker Hub'
    inputs:
      command: push
      repository: nhidayah26/flask-app-cicd
      tags: |
        v1
      containerRegistry: dockerhub-cicd


- job: CD
  displayName: 'Continuous Deployment'
  dependsOn: CI

  pool:
    name: minikube-local

  steps:
  - script: |
      echo "Current Kubernetes nodes:"
      kubectl get nodes

      echo ""
      echo "Checking MySQL secret..."
      kubectl get secret mysql-secret -n flask-demo

      echo ""
      echo "Deploying Flask application..."
      kubectl apply -f k8s/flask-deployment.yaml

      echo ""
      echo "Deploying Flask service..."
      kubectl apply -f k8s/flask-service.yaml

      echo ""
      echo "Checking Flask rollout..."
      kubectl rollout status deployment/flask-deployment -n flask-demo
    displayName: 'Deploy to Minikube'

