services:
  flask:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: