apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment
  namespace: flask-webapp-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp

  template:
    metadata:
      labels:
        app: flask-webapp

    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers: 
        - name: flask-webapp
          image: nhidayah26/flask-webapp-demo:v1

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: mysql
              
            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: comments_db

            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
